HyperParameter Tuning using Keras Tuner by Prince kumar

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/diabetes.csv')

In [ ]:
df.shape

(768, 9)

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.corr(
)['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
ss = StandardScaler()

In [ ]:
x_scaled = ss.fit_transform(X)

In [ ]:
x_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(16,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 833 (3.25 KB)

 Trainable params: 833 (3.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3845 - val_accuracy: 0.7532 - val_loss: 0.5535
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3837 - val_accuracy: 0.7662 - val_loss: 0.5547
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3820 - val_accuracy: 0.7662 - val_loss: 0.5516
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3817 - val_accuracy: 0.7727 - val_loss: 0.5526
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3818 - val_accuracy: 0.7597 - val_loss: 0.5500
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3799 - val_accuracy: 0.7597 - val_loss: 0.5505
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3805 - val_accuracy: 0.7727 - val_loss: 0.5528
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3774 - val_accuracy: 0.7597 - val_loss: 0.5493
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3773 - val_accuracy: 0.7662 - val_loss: 0.5582
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3783 - val_accuracy: 0.7662 - val_loss: 0.5656
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3767 - val_accuracy: 0.7597 - val_loss: 0.5619
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3759 - val_accuracy: 0.7662 - val_loss: 0.5606
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3748 - val_accuracy: 0.7532 - val_loss: 0.5556
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3753 - val_accuracy: 0.7727 - val_loss: 0.5592
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3730 - val_accuracy: 0.7662 - val_loss: 0.5547
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3736 - val_accuracy: 0.7597 - val_loss: 0.5603
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3710 - val_accuracy: 0.7597 - val_loss: 0.5597
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3724 - val_accuracy: 0.7727 - val_loss: 0.5541
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3686 - val_accuracy: 0.7662 - val_loss: 0.5517
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3685 - val_accuracy: 0.7727 - val_loss: 0.5535
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3672 - val_accuracy: 0.7662 - val_loss: 0.5600
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3667 - val_accuracy: 0.7597 - val_loss: 0.5619
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3664 - val_accuracy: 0.7727 - val_loss: 0.5553
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3650 - val_accuracy: 0.7662 - val_loss: 0.5619
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3626 - val_accuracy: 0.7727 - val_loss: 0.5630
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3633 - val_accuracy: 0.7792 - val_loss: 0.5583
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3630 - val_accuracy: 0.7532 - val_loss: 0.5651
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3612 - val_accuracy: 0.7597 - val_loss: 0.5636
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3601 - val_accuracy: 0.7662 - val_loss: 0.5659
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8388 - loss: 0.3585 - val_accuracy: 0.7597 - val_loss: 0.5676
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3586 - val_accuracy: 0.7597 - val_loss: 0.5732
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8339 - loss: 0.3566 - val_accuracy: 0.7662 - val_loss: 0.5678
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8388 - loss: 0.3583 - val_accuracy: 0.7662 - val_loss: 0.5682
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3563 - val_accuracy: 0.7727 - val_loss: 0.5664
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8388 - loss: 0.3543 - val_accuracy: 0.7597 - val_loss: 0.5701
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3540 - val_accuracy: 0.7597 - val_loss: 0.5707
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8322 - loss: 0.3508 - val_accuracy: 0.7597 - val_loss: 0.5719
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8339 - loss: 0.3518 - val_accuracy: 0.7597 - val_loss: 0.5699
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8388 - loss: 0.3504 - val_accuracy: 0.7597 - val_loss: 0.5736
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.3504 - val_accuracy: 0.7597 - val_loss: 0.5730
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3516 - val_accuracy: 0.7597 - val_loss: 0.5720
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3479 - val_accuracy: 0.7662 - val_loss: 0.5815
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3487 - val_accuracy: 0.7597 - val_loss: 0.5724
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3469 - val_accuracy: 0.7532 - val_loss: 0.5816
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3448 - val_accuracy: 0.7662 - val_loss: 0.5771
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8518 - loss: 0.3434 - val_accuracy: 0.7532 - val_loss: 0.5771
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3431 - val_accuracy: 0.7597 - val_loss: 0.5811
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3421 - val_accuracy: 0.7597 - val_loss: 0.5842
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3427 - val_accuracy: 0.7597 - val_loss: 0.5890
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3400 - val_accuracy: 0.7662 - val_loss: 0.5885
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3407 - val_accuracy: 0.7468 - val_loss: 0.5870
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3401 - val_accuracy: 0.7532 - val_loss: 0.5843
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3382 - val_accuracy: 0.7597 - val_loss: 0.5916
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3376 - val_accuracy: 0.7532 - val_loss: 0.5953
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3387 - val_accuracy: 0.7662 - val_loss: 0.5884
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3360 - val_accuracy: 0.7532 - val_loss: 0.5962
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3337 - val_accuracy: 0.7532 - val_loss: 0.5967
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3322 - val_accuracy: 0.7597 - val_loss: 0.6004
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3325 - val_accuracy: 0.7532 - val_loss: 0.5973
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3333 - val_accuracy: 0.7597 - val_loss: 0.5916
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3300 - val_accuracy: 0.7597 - val_loss: 0.6063
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3293 - val_accuracy: 0.7597 - val_loss: 0.6024
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3290 - val_accuracy: 0.7532 - val_loss: 0.6026
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3272 - val_accuracy: 0.7532 - val_loss: 0.6100
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3275 - val_accuracy: 0.7468 - val_loss: 0.6121
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3263 - val_accuracy: 0.7662 - val_loss: 0.6028
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3233 - val_accuracy: 0.7468 - val_loss: 0.6081
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3244 - val_accuracy: 0.7597 - val_loss: 0.6116
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3226 - val_accuracy: 0.7403 - val_loss: 0.6175
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3220 - val_accuracy: 0.7532 - val_loss: 0.6146
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3212 - val_accuracy: 0.7727 - val_loss: 0.6154
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3207 - val_accuracy: 0.7662 - val_loss: 0.6228
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3191 - val_accuracy: 0.7597 - val_loss: 0.6190
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3197 - val_accuracy: 0.7468 - val_loss: 0.6136
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3182 - val_accuracy: 0.7338 - val_loss: 0.6161
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3168 - val_accuracy: 0.7468 - val_loss: 0.6221
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3156 - val_accuracy: 0.7532 - val_loss: 0.6232
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3173 - val_accuracy: 0.7662 - val_loss: 0.6173
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3148 - val_accuracy: 0.7597 - val_loss: 0.6188
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3162 - val_accuracy: 0.7662 - val_loss: 0.6190
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3133 - val_accuracy: 0.7532 - val_loss: 0.6292
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3118 - val_accuracy: 0.7597 - val_loss: 0.6217
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3113 - val_accuracy: 0.7532 - val_loss: 0.6367
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3098 - val_accuracy: 0.7468 - val_loss: 0.6295
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3105 - val_accuracy: 0.7403 - val_loss: 0.6273
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3075 - val_accuracy: 0.7468 - val_loss: 0.6342
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3082 - val_accuracy: 0.7468 - val_loss: 0.6390
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8632 - loss: 0.3067 - val_accuracy: 0.7468 - val_loss: 0.6350
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3069 - val_accuracy: 0.7597 - val_loss: 0.6380
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.3065 - val_accuracy: 0.7468 - val_loss: 0.6403
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3045 - val_accuracy: 0.7597 - val_loss: 0.6411
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3048 - val_accuracy: 0.7468 - val_loss: 0.6359
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3038 - val_accuracy: 0.7532 - val_loss: 0.6483
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3035 - val_accuracy: 0.7597 - val_loss: 0.6457
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3046 - val_accuracy: 0.7597 - val_loss: 0.6445
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3005 - val_accuracy: 0.7662 - val_loss: 0.6473
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3002 - val_accuracy: 0.7532 - val_loss: 0.6484
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2994 - val_accuracy: 0.7532 - val_loss: 0.6497
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2976 - val_accuracy: 0.7468 - val_loss: 0.6478
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.2967 - val_accuracy: 0.7468 - val_loss: 0.6564

Selecting the best Optimizer for our Problem

In [ ]:
!pip install -q -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 5.2 MB/s eta 0:00:00

In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(16,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  optimizer=hp.Choice('Optimerzer',values = ['adam','sgd','rmsprop','adadelta','adamw','adagrad','adamax','adafactor','nadam','ftrl','loin','lamb','muon'])

  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=10)

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'Optimerzer': 'rmsprop'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 833 (3.25 KB)

 Trainable params: 833 (3.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test),initial_epoch=5)

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - accuracy: 0.7573 - loss: 0.4810 - val_accuracy: 0.7857 - val_loss: 0.4939
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4687 - val_accuracy: 0.7857 - val_loss: 0.4928
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4609 - val_accuracy: 0.7857 - val_loss: 0.4940
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4550 - val_accuracy: 0.7792 - val_loss: 0.4932
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4502 - val_accuracy: 0.7792 - val_loss: 0.4943
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4463 - val_accuracy: 0.7857 - val_loss: 0.4944
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4423 - val_accuracy: 0.7792 - val_loss: 0.4955
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4391 - val_accuracy: 0.7792 - val_loss: 0.5024
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4370 - val_accuracy: 0.7792 - val_loss: 0.4996
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.5017
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4318 - val_accuracy: 0.7857 - val_loss: 0.5035
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4303 - val_accuracy: 0.7857 - val_loss: 0.5043
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4273 - val_accuracy: 0.7857 - val_loss: 0.5035
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4260 - val_accuracy: 0.7792 - val_loss: 0.5064
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4231 - val_accuracy: 0.7857 - val_loss: 0.5131
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4221 - val_accuracy: 0.7792 - val_loss: 0.5136
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4203 - val_accuracy: 0.7792 - val_loss: 0.5154
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4186 - val_accuracy: 0.7792 - val_loss: 0.5140
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4163 - val_accuracy: 0.7792 - val_loss: 0.5158
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4151 - val_accuracy: 0.7792 - val_loss: 0.5194
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4130 - val_accuracy: 0.7792 - val_loss: 0.5210
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4110 - val_accuracy: 0.7727 - val_loss: 0.5199
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4106 - val_accuracy: 0.7727 - val_loss: 0.5252
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4089 - val_accuracy: 0.7727 - val_loss: 0.5282
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4070 - val_accuracy: 0.7727 - val_loss: 0.5270
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4061 - val_accuracy: 0.7662 - val_loss: 0.5336
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4050 - val_accuracy: 0.7727 - val_loss: 0.5309
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4038 - val_accuracy: 0.7532 - val_loss: 0.5319
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4031 - val_accuracy: 0.7468 - val_loss: 0.5343
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4006 - val_accuracy: 0.7597 - val_loss: 0.5319
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3999 - val_accuracy: 0.7532 - val_loss: 0.5388
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3987 - val_accuracy: 0.7468 - val_loss: 0.5430
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3987 - val_accuracy: 0.7468 - val_loss: 0.5396
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3963 - val_accuracy: 0.7468 - val_loss: 0.5416
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5384
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3949 - val_accuracy: 0.7468 - val_loss: 0.5426
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3932 - val_accuracy: 0.7662 - val_loss: 0.5393
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3929 - val_accuracy: 0.7532 - val_loss: 0.5416
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3921 - val_accuracy: 0.7532 - val_loss: 0.5443
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3900 - val_accuracy: 0.7468 - val_loss: 0.5487
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3896 - val_accuracy: 0.7662 - val_loss: 0.5496
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3886 - val_accuracy: 0.7662 - val_loss: 0.5483
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3878 - val_accuracy: 0.7403 - val_loss: 0.5531
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3873 - val_accuracy: 0.7597 - val_loss: 0.5522
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3860 - val_accuracy: 0.7597 - val_loss: 0.5532
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3849 - val_accuracy: 0.7597 - val_loss: 0.5542
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3844 - val_accuracy: 0.7403 - val_loss: 0.5565
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3830 - val_accuracy: 0.7403 - val_loss: 0.5614
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3825 - val_accuracy: 0.7662 - val_loss: 0.5589
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3817 - val_accuracy: 0.7468 - val_loss: 0.5580
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3802 - val_accuracy: 0.7532 - val_loss: 0.5598
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3793 - val_accuracy: 0.7597 - val_loss: 0.5608
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3790 - val_accuracy: 0.7532 - val_loss: 0.5616
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3780 - val_accuracy: 0.7468 - val_loss: 0.5651
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3768 - val_accuracy: 0.7468 - val_loss: 0.5640
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3756 - val_accuracy: 0.7597 - val_loss: 0.5650
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3743 - val_accuracy: 0.7468 - val_loss: 0.5638
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3744 - val_accuracy: 0.7662 - val_loss: 0.5639
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3742 - val_accuracy: 0.7403 - val_loss: 0.5678
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3725 - val_accuracy: 0.7597 - val_loss: 0.5707
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3723 - val_accuracy: 0.7597 - val_loss: 0.5667
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3712 - val_accuracy: 0.7597 - val_loss: 0.5676
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3704 - val_accuracy: 0.7597 - val_loss: 0.5715
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3693 - val_accuracy: 0.7597 - val_loss: 0.5698
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3686 - val_accuracy: 0.7597 - val_loss: 0.5717
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3682 - val_accuracy: 0.7597 - val_loss: 0.5739
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3669 - val_accuracy: 0.7468 - val_loss: 0.5765
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3660 - val_accuracy: 0.7532 - val_loss: 0.5786
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3660 - val_accuracy: 0.7403 - val_loss: 0.5808
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3639 - val_accuracy: 0.7532 - val_loss: 0.5786
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3636 - val_accuracy: 0.7532 - val_loss: 0.5815
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3630 - val_accuracy: 0.7597 - val_loss: 0.5847
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3618 - val_accuracy: 0.7468 - val_loss: 0.5819
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3612 - val_accuracy: 0.7468 - val_loss: 0.5821
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3598 - val_accuracy: 0.7468 - val_loss: 0.5870
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3605 - val_accuracy: 0.7597 - val_loss: 0.5866
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3582 - val_accuracy: 0.7468 - val_loss: 0.5833
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3578 - val_accuracy: 0.7597 - val_loss: 0.5854
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3573 - val_accuracy: 0.7532 - val_loss: 0.5903
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3563 - val_accuracy: 0.7468 - val_loss: 0.5931
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3559 - val_accuracy: 0.7662 - val_loss: 0.5919
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3558 - val_accuracy: 0.7403 - val_loss: 0.5942
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3538 - val_accuracy: 0.7403 - val_loss: 0.5963
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3528 - val_accuracy: 0.7468 - val_loss: 0.5985
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8453 - loss: 0.3521 - val_accuracy: 0.7403 - val_loss: 0.5999
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8518 - loss: 0.3513 - val_accuracy: 0.7403 - val_loss: 0.5977
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8518 - loss: 0.3503 - val_accuracy: 0.7468 - val_loss: 0.6012
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8550 - loss: 0.3492 - val_accuracy: 0.7403 - val_loss: 0.6024
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8550 - loss: 0.3487 - val_accuracy: 0.7403 - val_loss: 0.6006
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8534 - loss: 0.3485 - val_accuracy: 0.7338 - val_loss: 0.6043
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8550 - loss: 0.3464 - val_accuracy: 0.7468 - val_loss: 0.5990
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3466 - val_accuracy: 0.7403 - val_loss: 0.6023
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8534 - loss: 0.3452 - val_accuracy: 0.7468 - val_loss: 0.6013
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8502 - loss: 0.3456 - val_accuracy: 0.7532 - val_loss: 0.6034
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3437 - val_accuracy: 0.7403 - val_loss: 0.6088

Selecting the Number of Neurons in layer

In [79]:
def build_model_Neuron(hp):

  model2 = Sequential()
  units = hp.Int('units',min_value=8,max_value=64,step=8)

  model2.add(Dense(units=units,activation='relu',input_dim=8))
  model2.add(Dense(1,activation='sigmoid'))

  model2.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model2

In [81]:
tuner_Neuron = kt.RandomSearch(
    build_model_Neuron,
    objective='val_accuracy',
    max_trials=10,
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [82]:
tuner_Neuron.search(
    x_train, y_train,
    epochs=10,
    validation_data=(x_test, y_test)
)

Trial 7 Complete [00h 00m 04s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 35s

In [83]:
tuner_Neuron.get_best_hyperparameters()[0].values

{'units': 56}

In [84]:
model= tuner_Neuron.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [86]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test),initial_epoch=10)

Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4140 - val_accuracy: 0.7727 - val_loss: 0.5376
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4134 - val_accuracy: 0.7727 - val_loss: 0.5381
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4128 - val_accuracy: 0.7727 - val_loss: 0.5388
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4128 - val_accuracy: 0.7662 - val_loss: 0.5386
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4115 - val_accuracy: 0.7727 - val_loss: 0.5413
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4115 - val_accuracy: 0.7727 - val_loss: 0.5423
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4106 - val_accuracy: 0.7727 - val_loss: 0.5426
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4105 - val_accuracy: 0.7662 - val_loss: 0.5425
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4101 - val_accuracy: 0.7662 - val_loss: 0.5411
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4094 - val_accuracy: 0.7662 - val_loss: 0.5429
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4090 - val_accuracy: 0.7662 - val_loss: 0.5427
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4087 - val_accuracy: 0.7662 - val_loss: 0.5463
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4080 - val_accuracy: 0.7662 - val_loss: 0.5451
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4079 - val_accuracy: 0.7597 - val_loss: 0.5455
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4074 - val_accuracy: 0.7662 - val_loss: 0.5443
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4069 - val_accuracy: 0.7597 - val_loss: 0.5452
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4064 - val_accuracy: 0.7597 - val_loss: 0.5470
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4059 - val_accuracy: 0.7532 - val_loss: 0.5438
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4052 - val_accuracy: 0.7597 - val_loss: 0.5416
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4051 - val_accuracy: 0.7532 - val_loss: 0.5433
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4045 - val_accuracy: 0.7532 - val_loss: 0.5403
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4042 - val_accuracy: 0.7532 - val_loss: 0.5411
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4037 - val_accuracy: 0.7597 - val_loss: 0.5447
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4033 - val_accuracy: 0.7532 - val_loss: 0.5465
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4025 - val_accuracy: 0.7532 - val_loss: 0.5461
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4022 - val_accuracy: 0.7597 - val_loss: 0.5450
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4023 - val_accuracy: 0.7532 - val_loss: 0.5436
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4019 - val_accuracy: 0.7532 - val_loss: 0.5471
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4008 - val_accuracy: 0.7403 - val_loss: 0.5505
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4009 - val_accuracy: 0.7403 - val_loss: 0.5509
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4007 - val_accuracy: 0.7403 - val_loss: 0.5499
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4003 - val_accuracy: 0.7403 - val_loss: 0.5488
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.3995 - val_accuracy: 0.7468 - val_loss: 0.5454
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3991 - val_accuracy: 0.7468 - val_loss: 0.5455
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.3985 - val_accuracy: 0.7468 - val_loss: 0.5474
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.3988 - val_accuracy: 0.7468 - val_loss: 0.5453
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.3976 - val_accuracy: 0.7468 - val_loss: 0.5466
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3974 - val_accuracy: 0.7468 - val_loss: 0.5492
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.3972 - val_accuracy: 0.7403 - val_loss: 0.5516
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.3971 - val_accuracy: 0.7403 - val_loss: 0.5506
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8094 - loss: 0.3966 - val_accuracy: 0.7403 - val_loss: 0.5533
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3956 - val_accuracy: 0.7468 - val_loss: 0.5495
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3960 - val_accuracy: 0.7403 - val_loss: 0.5519
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.3953 - val_accuracy: 0.7532 - val_loss: 0.5508
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3947 - val_accuracy: 0.7532 - val_loss: 0.5506
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3945 - val_accuracy: 0.7403 - val_loss: 0.5538
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3943 - val_accuracy: 0.7403 - val_loss: 0.5547
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3938 - val_accuracy: 0.7403 - val_loss: 0.5553
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3935 - val_accuracy: 0.7532 - val_loss: 0.5544
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3929 - val_accuracy: 0.7468 - val_loss: 0.5550
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3927 - val_accuracy: 0.7403 - val_loss: 0.5548
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3925 - val_accuracy: 0.7468 - val_loss: 0.5539
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3917 - val_accuracy: 0.7468 - val_loss: 0.5540
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3919 - val_accuracy: 0.7403 - val_loss: 0.5567
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3909 - val_accuracy: 0.7403 - val_loss: 0.5564
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3910 - val_accuracy: 0.7468 - val_loss: 0.5559
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3899 - val_accuracy: 0.7468 - val_loss: 0.5570
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3899 - val_accuracy: 0.7532 - val_loss: 0.5571
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3895 - val_accuracy: 0.7403 - val_loss: 0.5588
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3893 - val_accuracy: 0.7468 - val_loss: 0.5569
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3891 - val_accuracy: 0.7403 - val_loss: 0.5583
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3883 - val_accuracy: 0.7403 - val_loss: 0.5576
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3882 - val_accuracy: 0.7403 - val_loss: 0.5582
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3878 - val_accuracy: 0.7403 - val_loss: 0.5578
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3878 - val_accuracy: 0.7338 - val_loss: 0.5595
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3869 - val_accuracy: 0.7338 - val_loss: 0.5572
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3869 - val_accuracy: 0.7403 - val_loss: 0.5586
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3861 - val_accuracy: 0.7338 - val_loss: 0.5597
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3856 - val_accuracy: 0.7338 - val_loss: 0.5592
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3855 - val_accuracy: 0.7338 - val_loss: 0.5610
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3853 - val_accuracy: 0.7403 - val_loss: 0.5589
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3853 - val_accuracy: 0.7468 - val_loss: 0.5572
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3842 - val_accuracy: 0.7468 - val_loss: 0.5576
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3838 - val_accuracy: 0.7403 - val_loss: 0.5619
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3831 - val_accuracy: 0.7403 - val_loss: 0.5634
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3836 - val_accuracy: 0.7403 - val_loss: 0.5630
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3832 - val_accuracy: 0.7338 - val_loss: 0.5644
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3828 - val_accuracy: 0.7403 - val_loss: 0.5652
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3821 - val_accuracy: 0.7468 - val_loss: 0.5599
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3818 - val_accuracy: 0.7403 - val_loss: 0.5645
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3816 - val_accuracy: 0.7403 - val_loss: 0.5610
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3811 - val_accuracy: 0.7403 - val_loss: 0.5625
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3809 - val_accuracy: 0.7468 - val_loss: 0.5612
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3804 - val_accuracy: 0.7403 - val_loss: 0.5633
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3805 - val_accuracy: 0.7338 - val_loss: 0.5677
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3798 - val_accuracy: 0.7273 - val_loss: 0.5687
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3794 - val_accuracy: 0.7338 - val_loss: 0.5672
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3794 - val_accuracy: 0.7338 - val_loss: 0.5683
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3790 - val_accuracy: 0.7273 - val_loss: 0.5698
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3785 - val_accuracy: 0.7338 - val_loss: 0.5680

Selecting Number of Hidden Layer

In [112]:
def build_model_HiddenLayer(hp):

    model = Sequential()

    # input layer
    model.add(Dense(56, activation='relu', input_shape=(8,), name='inpt_layer'))

    # hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        model.add(Dense(
            units=56,
            activation='relu',
            name=f'hidden_{i}'   # ✅ fix here
        ))

    # output layer
    model.add(Dense(1, activation='sigmoid', name='output'))

    model.compile(
        optimizer='rmsprop',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [105]:
tuner_hidden = kt.RandomSearch(build_model_HiddenLayer,objective='val_accuracy',max_trials=5,directory='untitled_project',project_name='hiddeen')

In [106]:
tuner_hidden.search(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 07s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 30s

In [109]:
tuner_hidden.get_best_hyperparameters(num_trials=1)[0].values

{'num_layers': 2}

In [110]:
model = tuner_hidden.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [111]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test),initial_epoch=10)

Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.7915 - loss: 0.4258 - val_accuracy: 0.7727 - val_loss: 0.5175
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7948 - loss: 0.4132 - val_accuracy: 0.7727 - val_loss: 0.5185
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4079 - val_accuracy: 0.7727 - val_loss: 0.5204
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4048 - val_accuracy: 0.7532 - val_loss: 0.5307
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4000 - val_accuracy: 0.7792 - val_loss: 0.5304
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3925 - val_accuracy: 0.7403 - val_loss: 0.5236
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3924 - val_accuracy: 0.7597 - val_loss: 0.5421
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3861 - val_accuracy: 0.7727 - val_loss: 0.5386
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3841 - val_accuracy: 0.7273 - val_loss: 0.5398
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3819 - val_accuracy: 0.7662 - val_loss: 0.5539
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3751 - val_accuracy: 0.7468 - val_loss: 0.5478
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3670 - val_accuracy: 0.7532 - val_loss: 0.5424
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3616 - val_accuracy: 0.7532 - val_loss: 0.5481
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3571 - val_accuracy: 0.7403 - val_loss: 0.5521
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3562 - val_accuracy: 0.7468 - val_loss: 0.5683
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3494 - val_accuracy: 0.7532 - val_loss: 0.5530
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3474 - val_accuracy: 0.7403 - val_loss: 0.5650
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3426 - val_accuracy: 0.7532 - val_loss: 0.5705
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3380 - val_accuracy: 0.7338 - val_loss: 0.5800
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3339 - val_accuracy: 0.7597 - val_loss: 0.5719
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3265 - val_accuracy: 0.7532 - val_loss: 0.5850
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3192 - val_accuracy: 0.7597 - val_loss: 0.5817
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3192 - val_accuracy: 0.7273 - val_loss: 0.5943
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3186 - val_accuracy: 0.7468 - val_loss: 0.6093
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3081 - val_accuracy: 0.7468 - val_loss: 0.6027
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3019 - val_accuracy: 0.7403 - val_loss: 0.6150
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3032 - val_accuracy: 0.7273 - val_loss: 0.6120
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2918 - val_accuracy: 0.7273 - val_loss: 0.6136
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8746 - loss: 0.2980 - val_accuracy: 0.7273 - val_loss: 0.6298
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8779 - loss: 0.2878 - val_accuracy: 0.7468 - val_loss: 0.6544
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8811 - loss: 0.2803 - val_accuracy: 0.7597 - val_loss: 0.6415
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8876 - loss: 0.2729 - val_accuracy: 0.7208 - val_loss: 0.6548
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8893 - loss: 0.2732 - val_accuracy: 0.7403 - val_loss: 0.6653
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8909 - loss: 0.2651 - val_accuracy: 0.7597 - val_loss: 0.6654
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8860 - loss: 0.2569 - val_accuracy: 0.7403 - val_loss: 0.6803
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8925 - loss: 0.2553 - val_accuracy: 0.7403 - val_loss: 0.6683
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8990 - loss: 0.2514 - val_accuracy: 0.7273 - val_loss: 0.7141
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9007 - loss: 0.2517 - val_accuracy: 0.7403 - val_loss: 0.7077
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2420 - val_accuracy: 0.7273 - val_loss: 0.7217
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2391 - val_accuracy: 0.7338 - val_loss: 0.7024
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.2261 - val_accuracy: 0.7143 - val_loss: 0.7655
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2262 - val_accuracy: 0.7078 - val_loss: 0.7360
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9218 - loss: 0.2234 - val_accuracy: 0.7143 - val_loss: 0.7617
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.2179 - val_accuracy: 0.7338 - val_loss: 0.7543
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2164 - val_accuracy: 0.7208 - val_loss: 0.7686
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.2055 - val_accuracy: 0.7403 - val_loss: 0.7912
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2107 - val_accuracy: 0.7143 - val_loss: 0.8055
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.2017 - val_accuracy: 0.7273 - val_loss: 0.8167
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1946 - val_accuracy: 0.7078 - val_loss: 0.8339
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1924 - val_accuracy: 0.7143 - val_loss: 0.8333
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9381 - loss: 0.1812 - val_accuracy: 0.6948 - val_loss: 0.8628
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9349 - loss: 0.1865 - val_accuracy: 0.7143 - val_loss: 0.8425
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9300 - loss: 0.1810 - val_accuracy: 0.7143 - val_loss: 0.8711
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.1966 - val_accuracy: 0.7013 - val_loss: 0.9032
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1652 - val_accuracy: 0.6948 - val_loss: 0.9197
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1715 - val_accuracy: 0.7013 - val_loss: 0.8896
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9463 - loss: 0.1629 - val_accuracy: 0.7078 - val_loss: 0.9191
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1591 - val_accuracy: 0.6883 - val_loss: 0.9259
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1636 - val_accuracy: 0.7208 - val_loss: 0.9213
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1483 - val_accuracy: 0.7013 - val_loss: 0.9995
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1465 - val_accuracy: 0.7078 - val_loss: 1.0044
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9495 - loss: 0.1493 - val_accuracy: 0.6883 - val_loss: 1.0513
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9544 - loss: 0.1370 - val_accuracy: 0.6948 - val_loss: 1.0206
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1282 - val_accuracy: 0.7013 - val_loss: 1.0069
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1261 - val_accuracy: 0.6883 - val_loss: 1.0452
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1279 - val_accuracy: 0.7208 - val_loss: 1.0176
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1273 - val_accuracy: 0.6883 - val_loss: 1.0615
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1224 - val_accuracy: 0.7208 - val_loss: 1.0512
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1165 - val_accuracy: 0.7013 - val_loss: 1.0880
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1213 - val_accuracy: 0.7013 - val_loss: 1.1003
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9658 - loss: 0.1190 - val_accuracy: 0.7078 - val_loss: 1.1381
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1072 - val_accuracy: 0.6753 - val_loss: 1.1137
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9707 - loss: 0.1033 - val_accuracy: 0.6818 - val_loss: 1.1530
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0995 - val_accuracy: 0.7143 - val_loss: 1.1451
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1058 - val_accuracy: 0.6688 - val_loss: 1.1700
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.1173 - val_accuracy: 0.7078 - val_loss: 1.2561
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1072 - val_accuracy: 0.7143 - val_loss: 1.2255
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1400 - val_accuracy: 0.6753 - val_loss: 1.1993
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9625 - loss: 0.1078 - val_accuracy: 0.7013 - val_loss: 1.2342
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.1031 - val_accuracy: 0.6948 - val_loss: 1.3184
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.1009 - val_accuracy: 0.6818 - val_loss: 1.2480
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0894 - val_accuracy: 0.6753 - val_loss: 1.3054
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0824 - val_accuracy: 0.6818 - val_loss: 1.2671
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0768 - val_accuracy: 0.6883 - val_loss: 1.2896
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0727 - val_accuracy: 0.6948 - val_loss: 1.3275
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0757 - val_accuracy: 0.6948 - val_loss: 1.3640
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0713 - val_accuracy: 0.6883 - val_loss: 1.3114
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0636 - val_accuracy: 0.7078 - val_loss: 1.3935
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0704 - val_accuracy: 0.6688 - val_loss: 1.4190
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0692 - val_accuracy: 0.6818 - val_loss: 1.4055

Selecting Best Model with Dropout and Early Stopping

In [113]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

def build_model_all(hp):

    tf.keras.backend.clear_session()   #  prevents graph issues

    model = Sequential()

    #  Tune number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=5)

    for i in range(num_layers):

        #  Tune neurons per layer
        units = hp.Int(f'units_{i}', min_value=8, max_value=128, step=8)

        #  Tune activation function
        activation = hp.Choice(f'activation_{i}', ['relu', 'tanh', 'sigmoid'])

        if i == 0:
            model.add(Dense(
                units=units,
                activation=activation,
                input_shape=(8,),
                name=f'dense_{i}'
            ))
        else:
            model.add(Dense(
                units=units,
                activation=activation,
                name=f'dense_{i}'
            ))

        #  Tune dropout
        dropout_rate = hp.Float(f'dropout_{i}', min_value=0.0, max_value=0.5, step=0.1)
        model.add(Dropout(rate=dropout_rate, name=f'dropout_{i}'))

    #  Output layer
    model.add(Dense(1, activation='sigmoid', name='output'))

    #  Tune optimizer
    optimizer_choice = hp.Choice('optimizer', ['adam', 'rmsprop', 'sgd'])

    #  Tune learning rate
    learning_rate = hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])

    if optimizer_choice == 'adam':
        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer_choice == 'rmsprop':
        optimizer = tf.keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [114]:
tuner = kt.RandomSearch(
    build_model_all,
    objective='val_accuracy',
    max_trials=50,   #  increase this
    directory='tuning_dir',
    project_name='full_tuning'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [116]:
tuner.search(
    x_train, y_train,
    epochs=30,
    validation_data=(x_test, y_test),
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=5)]
)

Trial 50 Complete [00h 00m 12s]
val_accuracy: 0.7597402334213257

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 08m 53s

In [117]:
tuner.get_best_hyperparameters(num_trials=1)[0].values

{'num_layers': 2,
 'units_0': 88,
 'activation_0': 'tanh',
 'dropout_0': 0.1,
 'optimizer': 'adam',
 'learning_rate': 0.0001,
 'units_1': 32,
 'activation_1': 'relu',
 'dropout_1': 0.30000000000000004,
 'units_2': 64,
 'activation_2': 'relu',
 'dropout_2': 0.30000000000000004,
 'units_3': 120,
 'activation_3': 'relu',
 'dropout_3': 0.1,
 'units_4': 48,
 'activation_4': 'tanh',
 'dropout_4': 0.2}

In [118]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [119]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_0 (Dense)                 │ (None, 88)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_0 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,673 (14.35 KB)

 Trainable params: 3,673 (14.35 KB)

 Non-trainable params: 0 (0.00 B)

In [122]:
model.fit(x_train,y_train,epochs=200,initial_epoch=30,validation_data=(x_test,y_test))

Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7899 - loss: 0.4513 - val_accuracy: 0.7727 - val_loss: 0.4948
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4460 - val_accuracy: 0.7727 - val_loss: 0.4951
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4457 - val_accuracy: 0.7727 - val_loss: 0.4953
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4439 - val_accuracy: 0.7662 - val_loss: 0.4951
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4422 - val_accuracy: 0.7662 - val_loss: 0.4947
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4446 - val_accuracy: 0.7662 - val_loss: 0.4950
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4487 - val_accuracy: 0.7727 - val_loss: 0.4955
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4351 - val_accuracy: 0.7727 - val_loss: 0.4955
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4437 - val_accuracy: 0.7662 - val_loss: 0.4961
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4427 - val_accuracy: 0.7662 - val_loss: 0.4960
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4491 - val_accuracy: 0.7662 - val_loss: 0.4963
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4398 - val_accuracy: 0.7662 - val_loss: 0.4963
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4396 - val_accuracy: 0.7727 - val_loss: 0.4960
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4350 - val_accuracy: 0.7662 - val_loss: 0.4967
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4517 - val_accuracy: 0.7662 - val_loss: 0.4965
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4429 - val_accuracy: 0.7727 - val_loss: 0.4960
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4490 - val_accuracy: 0.7727 - val_loss: 0.4968
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4378 - val_accuracy: 0.7727 - val_loss: 0.4968
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4342 - val_accuracy: 0.7662 - val_loss: 0.4965
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4468 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4347 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4424 - val_accuracy: 0.7727 - val_loss: 0.4964
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4481 - val_accuracy: 0.7727 - val_loss: 0.4959
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4423 - val_accuracy: 0.7727 - val_loss: 0.4961
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4457 - val_accuracy: 0.7727 - val_loss: 0.4973
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4413 - val_accuracy: 0.7727 - val_loss: 0.4974
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4487 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4490 - val_accuracy: 0.7727 - val_loss: 0.4969
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4425 - val_accuracy: 0.7727 - val_loss: 0.4969
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4566 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4433 - val_accuracy: 0.7727 - val_loss: 0.4970
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4344 - val_accuracy: 0.7727 - val_loss: 0.4965
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4378 - val_accuracy: 0.7727 - val_loss: 0.4967
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4339 - val_accuracy: 0.7727 - val_loss: 0.4961
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4368 - val_accuracy: 0.7727 - val_loss: 0.4963
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4493 - val_accuracy: 0.7727 - val_loss: 0.4967
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4398 - val_accuracy: 0.7727 - val_loss: 0.4967
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4356 - val_accuracy: 0.7727 - val_loss: 0.4975
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4358 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4455 - val_accuracy: 0.7727 - val_loss: 0.4980
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4383 - val_accuracy: 0.7662 - val_loss: 0.4982
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4451 - val_accuracy: 0.7662 - val_loss: 0.4985
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4340 - val_accuracy: 0.7662 - val_loss: 0.4982
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7720 - loss: 0.4483 - val_accuracy: 0.7662 - val_loss: 0.4975
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4370 - val_accuracy: 0.7662 - val_loss: 0.4968
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4388 - val_accuracy: 0.7662 - val_loss: 0.4973
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.4442 - val_accuracy: 0.7662 - val_loss: 0.4973
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4386 - val_accuracy: 0.7662 - val_loss: 0.4976
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4502 - val_accuracy: 0.7662 - val_loss: 0.4977
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4283 - val_accuracy: 0.7662 - val_loss: 0.4978
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4381 - val_accuracy: 0.7662 - val_loss: 0.4979
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4409 - val_accuracy: 0.7662 - val_loss: 0.4986
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4434 - val_accuracy: 0.7662 - val_loss: 0.4986
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4463 - val_accuracy: 0.7662 - val_loss: 0.4988
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4436 - val_accuracy: 0.7662 - val_loss: 0.4985
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4379 - val_accuracy: 0.7662 - val_loss: 0.4988
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4419 - val_accuracy: 0.7662 - val_loss: 0.4983
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4511 - val_accuracy: 0.7662 - val_loss: 0.4991
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4465 - val_accuracy: 0.7662 - val_loss: 0.4999
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4251 - val_accuracy: 0.7662 - val_loss: 0.4995
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4390 - val_accuracy: 0.7662 - val_loss: 0.5000
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4379 - val_accuracy: 0.7662 - val_loss: 0.4994
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4333 - val_accuracy: 0.7662 - val_loss: 0.5007
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4386 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4322 - val_accuracy: 0.7597 - val_loss: 0.5016
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4518 - val_accuracy: 0.7662 - val_loss: 0.5020
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4382 - val_accuracy: 0.7662 - val_loss: 0.5026
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4315 - val_accuracy: 0.7662 - val_loss: 0.5022
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4366 - val_accuracy: 0.7662 - val_loss: 0.5016
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4467 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4319 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4253 - val_accuracy: 0.7662 - val_loss: 0.5009
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4464 - val_accuracy: 0.7662 - val_loss: 0.5007
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4313 - val_accuracy: 0.7662 - val_loss: 0.5013
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4431 - val_accuracy: 0.7662 - val_loss: 0.5009
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4494 - val_accuracy: 0.7662 - val_loss: 0.5011
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4371 - val_accuracy: 0.7662 - val_loss: 0.5013
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4281 - val_accuracy: 0.7662 - val_loss: 0.5019
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4334 - val_accuracy: 0.7662 - val_loss: 0.5022
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4399 - val_accuracy: 0.7727 - val_loss: 0.5024
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4306 - val_accuracy: 0.7727 - val_loss: 0.5032
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4385 - val_accuracy: 0.7662 - val_loss: 0.5039
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4402 - val_accuracy: 0.7662 - val_loss: 0.5037
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4376 - val_accuracy: 0.7662 - val_loss: 0.5043
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4335 - val_accuracy: 0.7662 - val_loss: 0.5046
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4312 - val_accuracy: 0.7662 - val_loss: 0.5036
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4419 - val_accuracy: 0.7662 - val_loss: 0.5035
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4522 - val_accuracy: 0.7662 - val_loss: 0.5036
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4398 - val_accuracy: 0.7662 - val_loss: 0.5039
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4359 - val_accuracy: 0.7662 - val_loss: 0.5036
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4298 - val_accuracy: 0.7662 - val_loss: 0.5036
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4378 - val_accuracy: 0.7662 - val_loss: 0.5035
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4243 - val_accuracy: 0.7727 - val_loss: 0.5036
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4132 - val_accuracy: 0.7727 - val_loss: 0.5033
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4395 - val_accuracy: 0.7662 - val_loss: 0.5037
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4355 - val_accuracy: 0.7727 - val_loss: 0.5038
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4492 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4265 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4394 - val_accuracy: 0.7727 - val_loss: 0.5043
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4271 - val_accuracy: 0.7662 - val_loss: 0.5039
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4454 - val_accuracy: 0.7662 - val_loss: 0.5041
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4306 - val_accuracy: 0.7727 - val_loss: 0.5033
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4413 - val_accuracy: 0.7727 - val_loss: 0.5034
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4349 - val_accuracy: 0.7662 - val_loss: 0.5029
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4388 - val_accuracy: 0.7792 - val_loss: 0.5028
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4301 - val_accuracy: 0.7727 - val_loss: 0.5027
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4349 - val_accuracy: 0.7792 - val_loss: 0.5024
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4338 - val_accuracy: 0.7727 - val_loss: 0.5028
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4314 - val_accuracy: 0.7792 - val_loss: 0.5022
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4328 - val_accuracy: 0.7792 - val_loss: 0.5015
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4538 - val_accuracy: 0.7792 - val_loss: 0.5018
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4251 - val_accuracy: 0.7792 - val_loss: 0.5017
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4218 - val_accuracy: 0.7792 - val_loss: 0.5015
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4308 - val_accuracy: 0.7792 - val_loss: 0.5021
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4391 - val_accuracy: 0.7792 - val_loss: 0.5023
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4265 - val_accuracy: 0.7727 - val_loss: 0.5030
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4286 - val_accuracy: 0.7727 - val_loss: 0.5035
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4261 - val_accuracy: 0.7662 - val_loss: 0.5041
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4379 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4259 - val_accuracy: 0.7662 - val_loss: 0.5040
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4144 - val_accuracy: 0.7727 - val_loss: 0.5043
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4292 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4335 - val_accuracy: 0.7662 - val_loss: 0.5038
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4388 - val_accuracy: 0.7662 - val_loss: 0.5041
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4296 - val_accuracy: 0.7662 - val_loss: 0.5040
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4330 - val_accuracy: 0.7662 - val_loss: 0.5044
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4307 - val_accuracy: 0.7662 - val_loss: 0.5044
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4373 - val_accuracy: 0.7662 - val_loss: 0.5038
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4285 - val_accuracy: 0.7662 - val_loss: 0.5042
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4299 - val_accuracy: 0.7662 - val_loss: 0.5049
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4268 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 162/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4346 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 163/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4278 - val_accuracy: 0.7662 - val_loss: 0.5046
Epoch 164/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4357 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 165/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4311 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 166/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4444 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 167/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4224 - val_accuracy: 0.7662 - val_loss: 0.5052
Epoch 168/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4291 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 169/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4265 - val_accuracy: 0.7662 - val_loss: 0.5054
Epoch 170/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4339 - val_accuracy: 0.7662 - val_loss: 0.5061
Epoch 171/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4327 - val_accuracy: 0.7662 - val_loss: 0.5064
Epoch 172/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4372 - val_accuracy: 0.7662 - val_loss: 0.5064
Epoch 173/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4315 - val_accuracy: 0.7662 - val_loss: 0.5065
Epoch 174/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4239 - val_accuracy: 0.7662 - val_loss: 0.5064
Epoch 175/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4263 - val_accuracy: 0.7662 - val_loss: 0.5060
Epoch 176/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4284 - val_accuracy: 0.7662 - val_loss: 0.5055
Epoch 177/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4293 - val_accuracy: 0.7662 - val_loss: 0.5062
Epoch 178/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4378 - val_accuracy: 0.7727 - val_loss: 0.5059
Epoch 179/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4199 - val_accuracy: 0.7727 - val_loss: 0.5071
Epoch 180/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4256 - val_accuracy: 0.7727 - val_loss: 0.5073
Epoch 181/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4325 - val_accuracy: 0.7662 - val_loss: 0.5085
Epoch 182/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4267 - val_accuracy: 0.7727 - val_loss: 0.5083
Epoch 183/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4345 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 184/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4137 - val_accuracy: 0.7662 - val_loss: 0.5087
Epoch 185/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4241 - val_accuracy: 0.7727 - val_loss: 0.5080
Epoch 186/200